### PR TITLE
AUI-2080 Define UI attribute to update view if days count changes.

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by mairatma** [comment]
@brandizzi, can you take a look at my inline comments? Other than those all lgtm.

**Comment by brandizzi** [comment]
@mairatma I'll proceed to fix the problems. Should I send a new PR to @thiago-rocha  or directly to you?

**Comment by mairatma** [comment]
You can send the update directly to me, since it's just these things I pointed out :)

**Comment by brandizzi** [comment]
Ok, thanks! Resent as https://github.com/mairatma/alloy-ui/pull/305. Note that the fixes were squashed into the older commits, to avoid polluting the log.

**Comment by mairatma** [comment]
Closing since this was resent as https://github.com/mairatma/alloy-ui/pull/305.

**Pull request closed without merging**
