### PR TITLE
AUI-1835

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1835.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Pull request merged to [liferay/master](https://github.com/liferay/alloy-ui/commits/master).

**Comment by mairatma** [comment]
@jonmak08 we may need this on master-deprecated as well, since we've backported the scheduler changes that caused this, right?

**Comment by jonmak08** [comment]
Hey @mairatma,

I will backport to this master-deprecate when I release a new version of AUI.

Please let me know if you have any questions.  Thanks!

**Pull request closed without merging**
