### PR TITLE
AUI-2021 AUI-Popover should choose the best position according to the view port

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by thiago-rocha** [comment]
@fernandosouza

**Comment by fernandosouza** [comment]
I will check it out on these observations, @mairatma and @thiago-rocha. Thank you.

**Comment by mairatma** [comment]
Thanks @fernandosouza :)

**Comment by mairatma** [comment]
Closing since this was sent again through https://github.com/mairatma/alloy-ui/pull/268.

**Pull request closed without merging**
