### PR TITLE
AUI-1695 Create media field for adding image urls

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by mairatma** [comment]
You forgot to break the first commit into smaller changes, like I asked on the other pull request :)

Copying the comment from there here: 

"This first commit is so big that it makes it hard to review, it's changing 36 files. Can you break it up into smaller commits? You can have one commit just with the data editor changes for example (js module, demo and tests together), then another one with just the form field, and then another one with the form builder field and other form builder changes. That way it will be a lot easier for me to follow each module's changes independently, as well as making it easier for other people to go through the commit history once this gets pushed."

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
I've just added some minor inline comments, but after that the code looks good to me.

The only other thing is that I've noticed that some tests failed when I ran them on yeti for multiple browsers. Not sure if they're failing because this is not working well on IE or if it's some problem with cached images. Either way, can you investigate?

Also there are 2 tests that are failing on my machine even when run with `gulp test`.

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Closing since this has become stale after such a long time.

**Comment by thiago-rocha** [comment]
='(

*Thiago Rocha*
Software Engineer
+55 81 9953-1054
Skype: tprcin

Liferay Inc.
Enterprise. Open Source. For Life
www.liferay.com

**Pull request closed without merging**
