### PR TITLE
AUI-1876

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1876.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Hey @jonmak08 and @westonhancock, thanks for working on this! This feature will be really nice to have.

I've added some inline comments, but besides those I think the behavior that was implemented is different from the one described on the issue. The issue wants the timepicker popover to scroll down to the time closest to the currently displayed time, not the current time on the user's clock. The title of the issue may be misleading, but its attached image explains it better. Besides, it does seem that it would be more helpful to show a time closer to the last picked time, instead of the current time.

**Comment by westonhancock** [comment]
Hey @mairatma 

Thanks for the input. Did you want me to make those changes? Also, changing the functionality to scroll to the time closest to the currently displayed time will be no problem at all.

**Comment by mairatma** [comment]
Yep, that would be great. Thanks again!

**Comment by westonhancock** [comment]
If there is no default time value displayed (i.e. "Meeting at hh:mm") should I have the picker scroll to the time nearest the users clock or not scroll at all?

**Comment by mairatma** [comment]
I'm not sure what the best behavior would be in this case, but I think it makes sense to scroll to the current time, it's probably more useful to show that than to start at 12AM, so it's a good idea to try.

**Comment by mairatma** [comment]
I'm closing this since it has been sent again as a new pr (https://github.com/mairatma/alloy-ui/pull/209).

**Pull request closed without merging**
