### PR TITLE
AUI-1859 User shouldn't be able to move a field inside another with movableContent false

### PR DESCRIPTION
**Pull request by brunocoelho**

### CODE REVIEW

**Comment by mairatma** [comment]
Nice, good to see this didn't need much code.

Can you just add a test case that covers this use case?

**Comment by brunocoelho** [comment]
@mairatma updated.

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Pull request merged.

**Pull request closed without merging**
