### PR TITLE
AUI-1837

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1837.  I am not sure if we need unit tests for this since this is such a specialized case.  If you think we should, we can revisit and add a unit test for this scenario.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
I think that since this bug is important enough that we've added a fix for it, then it should be important for us to have a test to protect agains regressions. Tests are also good for documenting behavior that would otherwise be forgotten with time, so we're trying to always cover everything that we can.
So the code looks good to me, but it would be good to have tests for both the fix for the centering and the fix for zero height/width.

**Comment by jonmak08** [comment]
Hey @mairatma,

Not a problem.  We will add tests to this pull request as well.

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
Hey @mjbradford89,

Can we add some unit tests for this issue?  Can you resend me a new pull request once we have added them?

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/mjbradford89/alloy-ui/pull/60

**Pull request closed without merging**
