### PR TITLE
AUI-2087 - Revert changes from Import commits from private temporary alloy 2.0 repository (Git SHA ID: 1009a5cac1b82daa86e447685c17db2ca7208a78).  This causes an IE printing issue.

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by mairatma** [comment]
The commit called "Revert changes from Import commits from private temporary..." isn't actually reverting the specified commit, since the original commit was way bigger, so the name is misleading. Can you update the title to explain what it actually does?

Also, I saw in the [original pr](https://github.com/thiago-rocha/alloy-ui/pull/74) to Thiago that you requested the demos to be removed before pushing the code. I don't think we should remove them though, it's a good way to test the behavior, since it'd be hard to test this via a regular unit test. I think that the demos just need to have information on the steps needed for them to work (probably the ones you mentioned on the original pr, @jonmak08).

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by blzaugg** [comment]
I'll be refining the Demo and I'll reword the "Revert" Commit

**Comment by blzaugg** [comment]
New PR: https://github.com/mairatma/alloy-ui/pull/319

**Pull request closed without merging**
