### PR TITLE
[Technical Support] AUI-1856 Incorrect display of overnight events in monthly view

### PR DESCRIPTION
**Pull request by zsagia**
Hi Maira,

Please see my modified description on AUI-1856 ticket.

Thanks a lot for your help.

Regards,
 Zsaga

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks for all the fixes!

I still can't seem to be able to reproduce this one without your changes though. I've followed the repro steps on the issue on my master branch and the events are rendering correctly for me on both Month and Week views. Can you double check how this is behaving for you on master? And if this is still happening for you, can you post screenshots of it? The screenshots I see in the issue are about the Month view, but the description talks about problems on the week view, so I think those screenshots are outdated.

**Comment by zsagia** [comment]
Hey Maira,

I built latest aui master and made a new gif (aui-1856-before-fixing). This file contains a very simple steps to reproduce this issue.

Thanks a lot for your patient. :):)

Zsaga

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks, I see it now!
Pull request merged into [liferay/master](https://github.com/liferay/alloy-ui/commits/master).

**Pull request closed without merging**
