### PR TITLE
AUI-1836

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1836.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonmak08** [comment]
Hey @mairatma,

I have updated this pull request with the requested changes.  Can you please review again?

Please let me know if you have any questions.  Thanks!

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Pull request merged into [liferay/master-deprecated](https://github.com/liferay/alloy-ui/commits/master-deprecated).

**Pull request merged**
