### PR TITLE
AUI-1909

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1909. Can you check this issue to make sure it is good.  If it is, I can push it into the 2.0.x repo.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Can you explain to me how do we reproduce this issue just on AlloyUI, without liferay? I ask for this because I couldn't find a way to reproduce it myself and we need to make sure this is an AlloyUI issue before making changes on its side, as sometimes the issue is just on the code that uses the component instead of on the component itself, in which case the changes should be there.

**Comment by jonmak08** [comment]
Hey @westonhancock,

Can you describe how to reproduce this issue in AlloyUI?

Please let me know if you have any questions.  Thanks!

**Comment by westonhancock** [comment]
Hey @mairatma 

The issue exists when a stylesheet sets the `max-height` of the modal body in a modal that has some content and a footer and is configured to be maximized in the browser window. This happens because `fillHeight()` in widget-stdmod.js will attempt to set the `offsetHeight` of the modal body so that the modal will fill the browser window. If a `max-height` less than the new `offsetHeight` is set on the modal body `fillHeight()` will not be able to set the `offsetHeight` correctly. Instead, the `height` of the body node is set to the value meant for the `offsetHeight` resulting in overflow equal to the amount of padding on top and bottom of the body node. Let me know if you have any more questions about it.

/cc @jonmak08

**Comment by mairatma** [comment]
@westonhancock, could you send me the css and any config attributes that would be needed to repro this on the modal's demo page? I still can't figure out exactly in what state I need the modal to be to repro this, so if you could repro on the demo and send me the details it would be great.

**Comment by jonmak08** [comment]
Hey @westonhancock,

Can you send @mairatma the information to repo this issue in AUI?

Please let me know if you have any questions.  Thanks!

**Comment by westonhancock** [comment]
Yeah, I'll send it over asap.

**Comment by westonhancock** [comment]
Hey @mairatma 

To reproduce the issue in AUI add this to the demo page:

```html
<style type="text/css">
    .modal .modal-body {
        padding: 15px;
        max-height: 400px;
        box-sizing: initial;
    }
</style>
```

and this to the end of the script in the demo page:

```javascript
resizeToFitWindow(modal);

function resizeToFitWindow (element) {
    var height = Y.DOM.winHeight() * 0.95;
    var width = Y.DOM.winWidth() * 0.95;

    element.set('height', height);
    element.set('width', width);
}

modal.align();
```

I was able to fix the issue with `box-sizing: border-box;` which is not globally applied to modals in portal 6.2.x. Although this issue is fixable with CSS I believe it is still a bug since the intended function of setting the offsetHeight is not completed successfully unless the `max-height` is cleared first. Let me know what you think and if you have any questions.

**Comment by westonhancock** [comment]
One additional note about the demo. The javascript mentioned in the last comment is just an automated resize. The behavior would be the same if you quickly resized the modal vertically past the set `max-height` manually.

**Comment by mairatma** [comment]
Oh, I see now, thank you for the explanation, this makes sense. @jonmak08  can push it to 2.0.x :)

**Comment by jonmak08** [comment]
Hey @mairatma,

I'll push this in.  Thanks!

**Pull request closed without merging**
