### PR TITLE
AUI-1755 Button for adding page breaks should be on the left of the button to add rows

### PR DESCRIPTION
**Pull request by brunocoelho**

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
I've noticed that clicking on the page break button is now creating both a row and a page break, when it should be only creating the page break. Maybe our click listener for adding rows is conflicting with the page break button now, can you take a look?

Also, I see some form builder unit test failures right now. They may be related to the page break button working incorrectly though, so maybe fixing that will fix them as well.

**Comment by brunocoelho** [comment]
@mairatma updated!

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
