### PR TITLE
AUI-2060

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-2060.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by zxdgoal** [comment]
The pull request of AUI-2040 in the case that you want its context.

https://github.com/mairatma/alloy-ui/pull/275

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonmak08** [comment]
Hey @zxdgoal,

Can you review @mairatma's comments and add new tests and send an updated pull request?

Please let me know if you have any questions.  Thanks!

**Comment by zxdgoal** [comment]
I see.

I will take care of them.

Thanks
John.

**Comment by jonmak08** [comment]
Thanks @zxdgoal!

**Comment by zxdgoal** [comment]
Hey Maira

I have finished the fix.

But I have a problem on the testing.

I do not know how to simulate change event for input to trigger the validateField method.

See https://github.com/zxdgoal/alloy-ui/commit/9832d55e91cf961856a763c49d65a93413a856a7

Could you give me some hints?

Thanks
John.

**Comment by mairatma** [comment]
Sure, you just need to call `simulate('change')` on a checkbox in the test, similar to how we test click events for aui-dropdown here: https://github.com/liferay/alloy-ui/blob/0f7979870e0646b87fa8ffcdd2a57d64f0727839/src/aui-dropdown/tests/unit/js/tests.js#L61.
Note that for this to work your test has to include `node-event-simulate`, like this: https://github.com/liferay/alloy-ui/blob/0f7979870e0646b87fa8ffcdd2a57d64f0727839/src/aui-dropdown/tests/unit/js/tests.js#L262.

**Comment by zxdgoal** [comment]
Thank you.

I did try ``input.simulate('change');`` in https://github.com/zxdgoal/alloy-ui/commit/9832d55e91cf961856a763c49d65a93413a856a7.

But after run ''gulp test'', it failed.

What is wired is that when I refresh index.html for the same test.

The test is passed

**Pull request closed without merging**
