### PR TITLE
AUI-1820 Form builder is not keyboard-accessible

### PR DESCRIPTION
**Pull request by brunocoelho**

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
This is working great, thanks!! In the end it wasn't too much code and it's easy to understand what's going on.

I just added some comments on the menu part of the code, then we'll merge.

**Comment by brunocoelho** [comment]
@mairatma updated. :bear:

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
