### PR TITLE
AUI-1815 Scroll shouldn't change while adding columns in layout builder

### PR DESCRIPTION
**Pull request by brunocoelho**

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunocoelho** [comment]
@mairatma updated!

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Pull request merged.

**Pull request closed without merging**
