### PR TITLE
AUI-1875

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1875. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
/cc @blzaugg 

Can you double check to make sure this solves the issue?

**Comment by mairatma** [comment]
I haven't tried this out yet, but from the title and the code it seems like this commit is disabling the checkLength method when a IME is being used. That will make the char counter allow any number of characters to be typed in this case, regardless of the max value. Is that what we want? From what I saw in the issue it seemed like the bug was that it was emptying the input value, so that needs to be fixed, but the expected result described there is still for the value to be trimmed to the max number of characters allowed.

**Comment by mairatma** [comment]
Also, it seems like the `compositionend` event is not supported by IE8, which AlloyUI still supports (https://developer.mozilla.org/en-US/docs/Web/Events/compositionend).

**Comment by blzaugg** [comment]
@jonmak08, your change works fine. Thanks.

@mairatma,
> it seems like this commit is disabling the checkLength method when a IME is being used

That's correct. 

> That will make the char counter allow any number of characters to be typed in this case, regardless of the max value. Is that what we want?

Yes. This is how native Chrome, Firefox, and IE 11 is doing it. They trim (or revert) the value after the IME tool finishes. IE 11 will stop displaying after the `maxlength`. Which I believe is problematic.

The reason we don't want to interrupt the IME during composition, is because for some language's characters, multiple key presses are required to get the desired character. So if I was at 9/10 on my input's `maxlength`, and I wanted some fancy character that required more than one key press, I don't want the browser or a framework interrupting/manipulating my input.

I can kind of demo this in native IE 11 in Japanese. Using keys `tsu` to make つ.
 1. Create an input with `maxlength="10"`
 1. Type 9 characters
 1. Type `tsu`

You'll only be able to see the `t`.The composition is still happening beyond the 10th character, you just can't see it. This is problematic for complicated codes.

We went even further with `char-counter`, and prevent the input from continuing at all. So you'd have cases were you cannot input the last character.

>  From what I saw in the issue it seemed like the bug was that it was emptying the input value, so that needs to be fixed, but the expected result described there is still for the value to be trimmed to the max number of characters allowed.

For Firefox, I'm not entirely sure why it blanked the value. I think it was likely some race condition between the IME tool and our setting the `value` attribute. I had done some various hacks around the issue, like timeouts, focus, blur, etc. In the end, they were not very graceful and we really should not have been interrupting the IME tool. The proper solution is to wait until `compositionend` fires to manipulate the `value`.

> Also, it seems like the compositionend event is not supported by IE8, which AlloyUI still supports (https://developer.mozilla.org/en-US/docs/Web/Events/compositionend).

This change won't effect any browser which isn't firing `compositionstart`, so their behavior will remain the same. I'm not able to test this fix on my IE8 VM (problems IME tools/langs). But IE 11 in Doc Mode 8 works as expected.

**Comment by mairatma** [comment]
Thank you so much for the detailed explanation! This makes total sense to me now.

It's a pity that this can't be fixed for IE8, but that's fine, at least this will work in the others.

Let me take a more thorough look at the code now.

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
This looks great, the only thing this is missing right now is a test case. This behavior should be simple to create a test for, you'd just need to simulate the compositionstart/compositionend events and make sure that if input events are triggered in the middle, no trimming will be made, while after compositionend is triggered all should work as before. Could you add the test?

**Comment by blzaugg** [comment]
Yes, I'll add a test. I wasn't sure whether I could test it accurately (without a human). But it doesn't hurt to simulate it; right?

Go ahead and close this PR.

**Comment by blzaugg** [comment]
https://github.com/mairatma/alloy-ui/pull/199

**Pull request closed without merging**
