### PR TITLE
AUI-1837

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1837.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks!

Pull request merged into [liferay/master](https://github.com/liferay/alloy-ui/commits/master).

**Comment by mairatma** [comment]
Hey guys, after this was pushed our jenkins build informed that the new image cropper test is failing on IE8. Take a look at the screenshot below:

screen shot 2015-02-05 at 10 20 56 am

@mjbradford89 Can you take a look at this failure and send a pr with the fix?

**Comment by jonmak08** [comment]
Hey @mairatma,

How do we see these jenkins build tests?

**Comment by mairatma** [comment]
You can see it at http://ci.liferay.org.es/jenkins/view/07.AlloyUI/job/liferay-alloyui-master-build/337/ if you have permissions. I don't remember where I got them but I can talk to Eduardo if necessary, he probably knows.

But I can reproduce this error when running on IE8 on my machine, so you'll probably need to run on IE8 to check if the fix is working anyway, and then you can see the failure there instead of going to jenkins for that. I recommend downloading a virtual machine with IE8 if you don't already have one, I got mine on https://www.modern.ie/en-us/virtualization-tools.

**Comment by mjbradford89** [comment]
@jonmak08 @mairatma 

Thanks for the heads up guys.  I'm working on it now and I'll send another pull when I have a fix.

**Comment by mairatma** [comment]
Thanks a lot!

**Comment by mjbradford89** [comment]
Submitted a new pull request: https://github.com/jonmak08/alloy-ui/pull/306.

Thanks!

**Pull request merged**
