### PR TITLE
[Technical-Supoort] AUI-1880 Overlapping events don't show up correctly

### PR DESCRIPTION
**Pull request by zsagia**
Hi Maira,

I'm sending you my solution for AUI-1880 where the basic issue was that plotted and overlapping events showed up incorrectly on "week" and "day" views.

Regarding of basic issue I noticed that we always get just first node of a plotted event. Thus, of course, the view of second node of plotted events aren't recalculated. During I tried to fix it I found some basic mistakes that's way I refactored this logic.

1. https://github.com/zsagia/alloy-ui/commit/3d8298a2c03a29c60a54843b44d093d42d2d269f#diff-f18ac5b7157479e7275559480fd13f04R258

We shouldn't iterate over the invisible events.

2. https://github.com/zsagia/alloy-ui/commit/3d8298a2c03a29c60a54843b44d093d42d2d269f#diff-f18ac5b7157479e7275559480fd13f04R947

Refactored logic. I used an array(specially important if we have more then 2 intersected events) for every worked events. Futhermore, based on evt._filtered value we modify nodeIndex (this can be 0 or 1). This will fix the plotted and overlapping mistake.

3. https://github.com/zsagia/alloy-ui/commit/3d8298a2c03a29c60a54843b44d093d42d2d269f#diff-f18ac5b7157479e7275559480fd13f04R1092

This is an unnecessary condition because we have handle it in another level.

Maira, if would be misunderstand-able please write me.

Thanks in advance,
 Zsaga

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks for working on this fix, I'm really sorry about the delay on reviewing them.

The code looks good, I've just added some comments for a few minor changes, but besides those, could you add a test that will cover the case you're fixing? We have this practice of only pushing commits with tests, it help both preventing regressions as well as documenting the behavior.

Also, all changes to an alloy-ui module are documented on the HISTORY.md file of that module, by adding a new entry to it linked to the jira issue that tracks the changes. Could you add the entry for this ticket on aui-scheduler HISTORY.md file?

**Comment by zsagia** [comment]
Hey Maira,

I fixed the mentioned deficiencies.

1. I wrote a new test case which contains 5 assertions.
2. I deleted the unused 'j' variable. The 'i' will be the correct.
3. I deleted the second "nodeIndex" decleration.
4. I run "gulp lint". I didn't know it so far. :)
5. I retested my solution on rebuilt master branch.

Thanks again,
 Zsaga

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks a lot for adding the tests and making the changes! I just added a couple of comments now, after that it will be ready to be pushed.

**Comment by zsagia** [comment]
Hi Maira,

Thanks a lot again for your review.

Regarding of your question:
"Is there a reason for creating a new counter variable, when j already works for that and was already being used before? If there isn't, then it's best to use j, since we won't need code to define it or update it ourselves."

The reason of I'm using "i" instead of "j" that we use this index variable to calculate correct width values.
In special cases when we have more intercessor events and we loop the "intercessors" we mustn't calculate again those events which has been already calculated.
"i" variable will be increased only when we have a new (not calculated) event.
"j" variable is increased in every iteration that's way it isn't good for us.

I hope I could clarify why we need this new variable.

Thank you again,
 Zsaga

**Comment by mairatma** [comment]
Oh, I see, I hadn't noticed the increment was inside the if statement, that makes total sense, thanks for the explanation.

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Pull request was merged into master. Thanks a lot for the fix!

**Pull request merged**
