### PR TITLE
[Technical Support] AUI-1854 Calendar, Week View, Events at the and of every day are not dis...

### PR DESCRIPTION
**Pull request by zsagia**
...played properly

Hi Maria,

I'm sending you Istvan's solution for AUI-1854. Based on ticket description you can reproduce it easily.

Please review this fix.

Thanks a lot,
 Zsaga

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Hey @zsagia, I'm not sure if I'm missing something, but I couldn't figure out how to follow the steps for reproducing this bug. How can I create an event that goes from 11:30pm from one day until 0:30 the other day? It seems like I'm not allowed to span more than one day when creating events through week and day views, and on month view I can't choose the time interval for the event.

Also, can you explain to me why replacing intersectHours with intersect fixes the problem?

**Comment by zsagia** [comment]
Hi Maira,

Sorry about our given reproduction steps wan't clear. Please see my attached images to AUI ticket.

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks @zsagia, this makes sense to me now.

**Pull request merged**
