### PR TITLE
AUI-1844 Trigger events for field creation/removal/edition

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by henvic** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Hey @thiago-rocha, as I mentioned in your other pull request, we've managed to push the `new-form-builder` branch to master, so can you send the changes made on this branch as a new pull request for me on master once you've updated it?

I'll close this since there will be another one then.

**Pull request closed without merging**
