### PR TITLE
AUI-1994 Adds borders as separators on the Form Builder

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
The code lgtm, but it seems like it's causing a test failure when all tests run together. If I run just the aui-layout tests they all pass, but if I run all alloy-ui tests, one of aui-layout-builder-resize-col tests is failing. Check the screenshot below:

screen shot 2016-01-26 at 10 01 07 am

Also, there's currently a lint error for a line that is bigger than it should, and I've added an inline comment for a small formatting problem too.

**Comment by thiago-rocha** [comment]
@fernandosouza

**Comment by fernandosouza** [comment]
Hi, @mairatma, @thiago-rocha. Thanks for reviewing but I can't reproduce the aui-layout-builder-resize-col test failure while running all tests together.

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Closing this since it was resent as https://github.com/mairatma/alloy-ui/pull/296.

**Pull request closed without merging**
