### PR TITLE
AUI-2040

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
@mairatma, we are unable to write a tests for these events because of browsers securely restrictions on file inputs.

**Comment by blzaugg** [comment]
@zxdgoal, I'll take care of the code squashing for this and future tickets. I'd rather review your work in individual, logical, commits that one big commit.

@mairatma, I'll send it over to @thiago-rocha. As for the test. I'm unable to test this as file input values cannot be scripting, for security reasons.

**Comment by mairatma** [comment]
Oh, sorry, I didn't see you comment about the tests before. It makes sense, it's hard to simulate file input changes, so it's fine in this case :)

Just to note, I also prefer smaller commits when reviewing, but in this case the smaller commits canceled each other, so in the end it became harder for me to review (and others to follow later) instead of easier, since I didn't even need to know about these 2 first commits. But I'm totally in support of breaking changes in separate commits for better readability, just also keeping in mind to have a clear commit history in the end.

**Comment by blzaugg** [comment]
https://github.com/thiago-rocha/alloy-ui/pull/41

**Pull request closed without merging**
