### PR TITLE
AUI-1619 Cannot set zIndex on Tooltip

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey @mairatma 

This is a back port of an AUI fix for portal of branch 6.2.X.

This issue is fixed for master as it is merged in AUI master and 3.0.x.

See the fix: https://github.com/eduardolundgren/alloy-ui/pull/761.

I updated the test class since it failed, according to https://github.com/liferay/alloy-ui/blob/master/src/aui-tooltip/tests/unit/js/tests.js#L163.

Please help review this issue 

Many thanks
John.

/cc @jonmak08

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks, this has been pushed to the 2.0.x liferay/alloy-ui branch

**Comment by jonmak08** [comment]
Hey @zxdgoal,

I will push in a new AUI zip and create a new release for this issue today.

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
Hey @zxdgoal,

I created a new AUI release with this issue at https://github.com/liferay/alloy-ui/releases/tag/2.0.0.58-deprecated.

Please let me know if you have any questions.  Thanks!

**Pull request merged**
