### PR TITLE
AUI-1900

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mairatma,

Attached is an update for http://issues.liferay.com/browse/AUI-1900. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
The code looks good, but it seems like it's causing a test failure for the aui-toggler-delegate test when I run `gulp test`. Can you guys check why it's failing?

**Comment by jonmak08** [comment]
Hey @westonhancock,

Can you take a look at the ```gulp test``` failure?

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
Nevermind.  I just saw @westonhancock has sent me a new pull request at https://github.com/jonmak08/alloy-ui/pull/316.

Please let me know if you have any questions.  Thanks @westonhancock !

**Pull request closed without merging**
